# Generated by Django 5.1.5 on 2025-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='available_dates',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
