# Generated by Django 5.1.5 on 2025-02-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20250217_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='spots_per_date',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
