# Generated by Django 5.1.5 on 2025-02-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_package_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='destinations',
            field=models.ManyToManyField(to='main_app.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
