# Generated by Django 5.1.5 on 2025-02-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_package_available_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='spots_per_date',
            new_name='total_spots',
        ),
    ]
