# Generated by Django 5.1.5 on 2025-02-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_booking_created_at_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
